#!/bin/sh


case $(echo -e "CONNECT\nDISCONNECT\nWIFI ON\nWIFI OFF" | dmenu -p "WIFI Options: " -l 4;) in
	CONNECT)
		wifiname=$(nmcli d wifi list | dmenu -p "Select WIFI" -l 20 | cut -d' ' -f9);
		pass=$(echo | dmenu -p "Password: " -i);
		nmcli d wifi connect $wifiname password $pass;
		;;
	DISCONNECT)
		internet=$(nmcli | grep "connected" | sed -n '1p' | cut -c 22-);
		nmcli con down id $internet;
		;;
	"WIFI ON")
		nmcli radio wifi on;
		;;
	"WIFI OFF")
		nmcli radio wifi off;
		;;
esac
